### ISSUE TITLE
It requires fabric loader >= 0.14.11 but latest quilt beta does not have it

### ISSUE THREAD

**Issue by Xoouu** [Bactrosaurus/bactromod#2]
The latest version 0.18.1-beta22 (I believe) does not have the required fabric loader. The latest version is currently incompatible with quilt at least until they update it.

**Comment by Bactrosaurus** [comment]
Update to 0.14.11 is already made (https://github.com/QuiltMC/quilt-loader/actions/runs/3653921875). You may try version 0.18.1-beta.23, they might already have included it there. However I won't downgrade to 0.14.10 as it should just take a few days for Quilt's beta to be released.

**Comment by TiLopes** [comment]
Beta 23 still doesn't have it so I just have to wait. Is it possible to toggle for example the gamma or only in mod menu?

**Comment by Bactrosaurus** [comment]
You could try the following:
1. Open the mod .jar file with any archive viewer (7zip etc.)
2. Drag out fabric.mod.json of the .jar archive
3. Edit the version of fabricloader to 0.14.10
4. Drag the edited file in the .jar archive again
Let me know if this is working for you, this is just a temporary solution.

UPDATE:
Fabric loader has been updated since this post was made. Don't use the presented option anymore!

**Comment by Xoouu** [comment]
I'll test it out tomorrow. Hope it works!
