### ISSUE TITLE
Sky Color Transition

### ISSUE THREAD

**Issue by Alpointernet** [Bactrosaurus/bactromod#3]
There is something wrong with the sky when i use this mod. The transition between white and blue between the lowest visible sky and the upper part of the sky is straight. Not smooth. ( I dont think I explained it very well so Im leaving a picture)
![Ekran görüntüsü_20230623_111021](https://github.com/Bactrosaurus/bactromod/assets/128177629/2f5f0a6b-5b95-4659-85f7-dd68abf3278c)

**Comment by Bactrosaurus** [comment]
This "transition" is actually caused by sky fog. It is disabled by default, but you can enable it either via ModMenu or in the Minecraft options in "Accessibility Settings" -> "BactroMod Settings" -> "Fog" -> "Disable sky fog" -> No.
However, I will consider enabling this type of fog by default, as I agree the game looks really ugly without.
