### ISSUE TITLE
Quilt Kotlin Libraries is unsupported

### ISSUE THREAD

**Issue by notrohit1702** [Bactrosaurus/bactromod#4]
The mod requires fabric language kotlin and throws an error when it is tried to be loaded with quilt kotlin libraries. However, some other mods require quilt kotlin libraries and do not support fabric language kotlin.

I would like to suggest that it should work with both quilt kotlin libraries **and** fabric language kotlin.

**Comment by Bactrosaurus** [comment]
Normally, Quilts Kotlin Libraries would be supported because they already have Fabric Language Kotlin integrated. The current problem is that Quilt still didn't update their Kotlin Libraries for Kotlin 1.9 and there's still no integration of Fabric Language Kotlin version 1.10. This Mod uses the newer dependencies, thats why you get an error message while starting Minecraft. I'm not sure on how well maintained Quilts Kotlin Library is, because last update was over a month ago and there's still no update available. From what I can tell Quilt always lags a bit behind regarding updating their libraries.
A short fix for your problem which might help:
1. Open bactromod-1.7.jar with any Archive Viewer (e.g. 7zip)
2. Drag fabric.mod.json out of the jar file into a seperate location
3. Open the fabric.mod.json which you dragged out with any text editor
4. Change the version of "fabric-language-kotlin" to ">=1.9.4+kotlin.1.8.22" and save the file
5. Drag the edited file back into the jar

Let me know if you had success with this method!

**Comment by notrohit1702** [comment]
I have already tried that method and can confirm it works. However, my issue was that I wanted to ship it in [my modpack](https://modrinth.com/modpack/minimalism) and adding it via an override would give you less credit. However, I realized that none of my mods require quilt kotlin libraries and work with fabric language kotlin too. So, I worked around it by replacing quilt kotlin libraries with fabric language kotlin.

Thank you for your patience! My issue is now solved.
